### ISSUE TITLE
Current commit does not work

### ISSUE THREAD

**Issue by seenickcode** [btford/angular-express-blog#6]
1.  Downloaded the main branch: https://github.com/btford/angular-express-blog.git
2.  npm install
3.  node app.js
4.  clicking 'new post' does not do anything. no js errors either.

(5)  (https://github.com/btford/angular-express-blog.git doesn't work either)

**Comment by sholtomaud** [comment]
It doesn't work out of the box for me either ... 

TypeError: Object function app(req, res){ app.handle(req, res); } has no method
'address'
    at Server.<anonymous> (C:\Users\ ... \angular-express-blog\app.js:55:69)
    at Server.g (events.js:175:14)
    at Server.EventEmitter.emit (events.js:92:17)
    at net.js:1052:10
    at process._tickCallback (node.js:415:13)
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)
    at node.js:901:3
